spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: testDB
            auto-index-creation: true
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: app.1
        producer:
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
api:
    weather:
        host: api.weather.gov
        path: points/
server:
    tomcat:
        threads:
            max: 200

jwt:
    token:
        secret: testsecret
        expired: 60000