spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: testDB
            auto-index-creation: true
api:
    weather:
        host: api.weather.gov
        path: points/
server:
    tomcat:
        threads:
            max: 200