spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: testDB
            auto-index-creation: true
    kafka:
        consumer:
            group-id: app.1
        bootstrap-servers: localhost:9092
    json:
        trusted:
            packages: com.practice.mongodb.document
api:
    weather:
        host: api.weather.gov
        path: points/
server:
    tomcat:
        threads:
            max: 200